### ISSUE TITLE
(Shadow sync): Executing sync request keep hanging

### ISSUE THREAD

**Issue by clitetailor** [aws-greengrass/aws-greengrass-shadow-manager#116]
**Describe the bug**
ShadowManager synchronization does not work correctly when updating shadow.

**To Reproduce**
1. Deploy Shadow Manager to Greengrass core device with synchronization setting enabled on named shadow. Strategy is set to real-time.
2. Go to Device Shadow Document page on AWS Console and update the Shadow Document.
3. Monitoring Greengrass device's logs

**Expected behavior**
Device shadow is synced, reported state is updated on AWS Console Shadow Document page.

**Actual behavior**
Device synchronization keep hanging up at "Executing sync request." log. There no reported state is being sent to IoT Core corresponding device shadow topic.

**Environment**
 - OS: Ubuntu 20.04
 - JDK version: OpenJDK 11.0.13
 - Nucleus version: 2.5.3
 - Shadow Manager version: 2.1.0

**Additional logs**
```
2022-02-18T19:53:30.260Z [INFO] (aws.greengrass.Cli-lifecycle) com.aws.greengrass.cli.CLIService: service-set-state. {serviceName=aws.greengrass.Cli, currentState=STARTING, newState=RUNNING}
2022-02-18T19:53:30.367Z [WARN] (pool-2-thread-32) com.aws.greengrass.shadowmanager.sync.model.FullShadowSyncRequest: Unable to find cloud shadow. {thing name=ThangLDGreengrassEmulator, shadow name=}
software.amazon.awssdk.services.iotdataplane.model.ResourceNotFoundException: No shadow exists with name: 'ThangLDGreengrassEmulator' (Service: IotDataPlane, Status Code: 404, Request ID: a11d1441-36ab-30fd-6fea-e0e28b8fe382, Extended Request ID: null)
        at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:123)
        at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:79)
        at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:59)
        at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:40)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:80)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
        at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
        at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
        at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:167)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:175)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
        at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
        at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
        at software.amazon.awssdk.services.iotdataplane.DefaultIotDataPlaneClient.getThingShadow(DefaultIotDataPlaneClient.java:221)
        at com.aws.greengrass.shadowmanager.sync.IotDataPlaneClientWrapper.getThingShadow(IotDataPlaneClientWrapper.java:89)
        at com.aws.greengrass.shadowmanager.sync.model.FullShadowSyncRequest.getCloudShadowDocument(FullShadowSyncRequest.java:502)
        at com.aws.greengrass.shadowmanager.sync.model.FullShadowSyncRequest.execute(FullShadowSyncRequest.java:107)
        at com.aws.greengrass.shadowmanager.sync.SyncHandler.lambda$new$0(SyncHandler.java:96)
        at com.aws.greengrass.util.RetryUtils.runWithRetry(RetryUtils.java:50)
        at com.aws.greengrass.shadowmanager.sync.SyncHandler.lambda$new$1(SyncHandler.java:94)
        at com.aws.greengrass.shadowmanager.sync.strategy.BaseSyncStrategy.lambda$new$0(BaseSyncStrategy.java:164)
        at com.aws.greengrass.shadowmanager.sync.strategy.BaseSyncStrategy.syncLoop(BaseSyncStrategy.java:389)
        at com.aws.greengrass.shadowmanager.sync.strategy.RealTimeSyncStrategy.syncLoop(RealTimeSyncStrategy.java:71)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)



2022-02-18T19:53:30.367Z [INFO] (pool-2-thread-32) com.aws.greengrass.shadowmanager.sync.model.FullShadowSyncRequest: Not performing full sync since both local and cloud versions are already in sync since they don't exist in local and cloud. {thing name=ThangLDGreengrassEmulator, shadow name=, cloud-version=0, local-version=0}
2022-02-18T19:53:30.368Z [INFO] (pool-2-thread-32) com.aws.greengrass.shadowmanager.ShadowManagerDAOImpl: Updating sync info. {thing name=ThangLDGreengrassEmulator, shadow name=, cloud-version=0, local-version=0}

2022-02-18T19:53:30.370Z [INFO] (pool-2-thread-32) com.aws.greengrass.shadowmanager.sync.strategy.BaseSyncStrategy: sync. Executing sync request. {Type=FullShadowSyncRequest, thing name=ThangLDGreengrassEmulator, shadow name=configuration}
2022-02-18T19:53:31.365Z [INFO] (pool-2-thread-30) com.aws.greengrass.deployment.DeploymentConfigMerger: merge-config. Removing services. {service-to-remove=[]}
2022-02-18T19:53:31.365Z [INFO] (pool-2-thread-30) com.aws.greengrass.deployment.activator.DeploymentActivator: merge-config. All services updated. {deploymentId=595d15aa-457d-4cca-a1c3-5a99185b85cf}
2022-02-18T19:53:31.365Z [INFO] (pool-2-thread-30) com.aws.greengrass.lifecyclemanager.UpdateSystemPolicyService: service-update-finish. {serviceName=UpdateSystemPolicyService, currentState=RUNNING}
2022-02-18T19:53:31.366Z [INFO] (pool-2-thread-29) com.aws.greengrass.deployment.DeploymentService: deployment-task-execution. Finished deployment task. {deploymentId=595d15aa-457d-4cca-a1c3-5a99185b85cf, serviceName=DeploymentService, currentState=RUNNING}
2022-02-18T19:53:41.691Z [INFO] (pool-2-thread-16) com.aws.greengrass.deployment.DeploymentService: Current deployment finished. {DeploymentId=arn:aws:greengrass:ap-southeast-1:614518134328:configuration:thing/ThangLDGreengrassEmulator:48, serviceName=DeploymentService, currentState=RUNNING}
2022-02-18T19:53:41.708Z [INFO] (pool-2-thread-16) com.aws.greengrass.deployment.DeploymentStatusKeeper: Stored deployment status. {DeploymentId=arn:aws:greengrass:ap-southeast-1:614518134328:configuration:thing/ThangLDGreengrassEmulator:48, DeploymentStatus=SUCCEEDED}
2022-02-18T19:53:41.709Z [INFO] (pool-2-thread-16) com.aws.greengrass.deployment.ShadowDeploymentListener: Updated reported state for deployment. {CONFIGURATION_ARN=arn:aws:greengrass:ap-southeast-1:614518134328:configuration:thing/ThangLDGreengrassEmulator:48, status=SUCCEEDED}
2022-02-18T19:53:41.721Z [INFO] (pool-2-thread-16) com.aws.greengrass.status.FleetStatusService: fss-status-update-published. Status update published to FSS. {serviceName=FleetStatusService, currentState=RUNNING}
2022-02-18T19:53:41.722Z [INFO] (pool-2-thread-16) com.aws.greengrass.deployment.DeploymentDirectoryManager: Persist link to last deployment. {link=/greengrass/v2/deployments/previous-success}
2022-02-18T19:53:41.722Z [INFO] (pool-2-thread-16) com.aws.greengrass.deployment.DeploymentDirectoryManager: Clean up link to earlier deployment. {link=/greengrass/v2/deployments/previous-success}
2022-02-18T19:54:07.542Z [INFO] (pool-2-thread-32) com.aws.greengrass.shadowmanager.sync.strategy.BaseSyncStrategy: sync. Executing sync request. {Type=LocalUpdateSyncRequest, thing name=ThangLDGreengrassEmulator, shadow name=configuration}
2022-02-18T19:54:07.593Z [INFO] (pool-2-thread-32) com.aws.greengrass.shadowmanager.ipc.UpdateThingShadowRequestHandler: Successfully updated shadow. {service-name=aws.greengrass.ShadowManager, thing name=ThangLDGreengrassEmulator, shadow name=configuration, local-version=42}
2022-02-18T19:54:07.617Z [INFO] (pool-2-thread-32) com.aws.greengrass.shadowmanager.ShadowManagerDAOImpl: Updating sync info. {thing name=ThangLDGreengrassEmulator, shadow name=configuration, cloud-version=105, local-version=42}
2022-02-18T19:54:07.619Z [INFO] (pool-2-thread-32) com.aws.greengrass.shadowmanager.sync.strategy.BaseSyncStrategy: sync. Executing sync request. {Type=CloudUpdateSyncRequest, thing name=ThangLDGreengrassEmulator, shadow name=configuration}
```

**Comment by nikkhilmuthye** [comment]
Hi Clite,

When you say the shadow is not getting synced, which shadow are you referring to? I see that the `ThangLDGreengrassEmulator` thing has been configured to sync the classic shadow as well as a named shadow called `configuration`. Shadow Manager was unable to find the classic shadow, so it did not sync that. But it was able to sync the `configuration` shadow.

**Comment by nhatpd-smartosc** [comment]
Hi @nikkhilmuthye,

Thanks for your reply. Yes the named `configuration` shadow was able to sync but it doesn't finish. You can see the final line of log is `Executing sync request.` and no other lines. As I understand if the syncing is successful, there must be the line `Finished processing sync requests` according to:

https://github.com/aws-greengrass/aws-greengrass-shadow-manager/blob/main/src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/BaseSyncStrategy.java#L458

The shadow reported state is not updated either.

**Comment by clitetailor** [comment]
Hi @nikkhilmuthye,

Thanks for your reply. Yes the named `configuration` shadow was able to sync but it doesn't finish. You can see the final line of log is `Executing sync request.` and there's no other line. As I understand if the syncing is successful, there must be the line `Finished processing sync requests` according to:

[https://github.com/aws-greengrass/aws-greengrass-shadow-manager/blob/main/src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/BaseSyncStrategy.java#L458](https://github.com/aws-greengrass/aws-greengrass-shadow-manager/blob/main/src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/BaseSyncStrategy.java?fbclid=IwAR0XA-wcZlw_a8eRsl-qspCiwhC_e3k8ofYd-vumO-vziVvZQw6FvAlds6k#L458)

The shadow reported state is not updated either.

**Comment by nikkhilmuthye** [comment]
Hi @clitetailor,

Since you have set the syncing strategy to `realTime`, that log line will only happen once when the Shadow Manager is shutting down. While performing Real Time syncing, the same while loop is being executed. This [Get Sync request function in real time sync class](https://github.com/aws-greengrass/aws-greengrass-shadow-manager/blob/main/src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/RealTimeSyncStrategy.java#L88) will block until there is a sync request to be executed.

If it were set to `periodic` sync strategy, then the log line you linked will be logged once all the sync requests are executed and there are no more left to sync for that interval run since [Get Sync request function in periodic sync class](https://github.com/aws-greengrass/aws-greengrass-shadow-manager/blob/main/src/main/java/com/aws/greengrass/shadowmanager/sync/strategy/PeriodicSyncStrategy.java#L93) will not block.

If you enable debug logging, you should see a `Successfully updated cloud shadow document` log line in the end. You can change the logging level by changing configuration for Nucleus. [Link for the Nucleus config](https://docs.aws.amazon.com/greengrass/v2/developerguide/greengrass-nucleus-component.html#:~:text=the%20core%20device.-,logging,Default%3A%20INFO,-format).

Let me know if you have any more questions.

Thanks,
Nikkhil

**Comment by thangldosc** [comment]
Hi @nikkhilmuthye,

Thanks for your information. I have some questions before closing the issue.

Because you said the ShadowManager works correctly, I wonder how the syncing works. According to [updating a shadow](https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-data-flow.html#update-pub-sub-topic-device), in order to report its current state, device should send a reported message back to AWS IoT Core `/update` topic but It seems like ShadowManager doesn't do that. So what is the purpose of the ShadowManager syncing stuff? Does it update the reported state according to the desired state changes. If it not so how should we report and manage the local state?

For example, if I have many components running on a same IoT Core device and all of them are listening on the same named shadow, do I need to create a specialized component to update the reported state back to cloud. And on the components, in order to react to desired state changes, do I have to merge the reported state with the delta/desired state manually (in Python) or do we have any utilities to help us to do that easily and precisely?

Thanks!
Clite

**Comment by clitetailor** [comment]
Hi @nikkhilmuthye,

Thanks for your information. I have some questions before closing the issue.

Because you said the ShadowManager works correctly, I wonder how the syncing works. According to [updating a shadow](https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-data-flow.html#update-pub-sub-topic-device), in order to report its current state, device should send a reported message back to AWS IoT Core `/update` topic but It seems like ShadowManager doesn't do that. So what is the purpose of the ShadowManager syncing stuff? Does it update the reported state according to the desired state changes. If it not so how should we report and manage the local state?

For example, if I have many components running on a same IoT Core device and all of them are listening on the same named shadow, do I need to create a specialized component to update the reported state back to cloud. And on the components, in order to react to desired state changes, do I have to merge the reported state with the delta/desired state manually (in Python) or do we have any utilities to help us to do that easily and precisely?

Thanks!
Clite

**Comment by nikkhilmuthye** [comment]
Hi @clitetailor,

So Shadow Manager is not going to change any state of the shadow until it receives an update from either AWS IoT or from a local custom component. According to the [IoT Greengrass documentation](https://docs.aws.amazon.com/greengrass/v2/developerguide/interact-with-shadows.html):

The [shadow manager](https://docs.aws.amazon.com/greengrass/v2/developerguide/shadow-manager-component.html) component enables your Greengrass components to create, update, and delete local shadows by using the [local shadow service](https://docs.aws.amazon.com/greengrass/v2/developerguide/ipc-local-shadows.html) and the local publish/subscribe shadow topics. The shadow manager also manages the storage of these local shadow documents on your core device, and handles the synchronization of shadow state information with cloud shadows.

So Shadow Manager will synchronize the local shadow if the cloud shadow is updated and update the cloud shadow if the local shadow is updated. But these shadows are updated only from the customer, either from a deployed code like lambda on the cloud or a deployed GG components on the device.

So in your example, you need to have a GG component deployed on the IoT device which is listening to updates from Shadow Manager whenever the local shadow is updated. This GG component will then process the shadow update and determine if it needs to update the local shadow or not based on the recent update and then send a message to [update the local shadow over IPC](https://docs.aws.amazon.com/greengrass/v2/developerguide/ipc-local-shadows.html#ipc-operation-updatethingshadow). Once Shadow Manager gets this update from the GG component, it will update the local shadow and then synchronize this update to the cloud shadow.

Hope this answers your question. Let me know if you need more clarification.

Thanks,
Nikkhil

**Comment by clitetailor** [comment]
@nikkhilmuthye Thank you very much for your support. The answer is very clear to me. I think I can close the ticket now.
